//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotekka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.AuthorBooks = new HashSet<AuthorBooks>();
            this.Loans = new HashSet<Loans>();
        }
    
        public int id { get; set; }
        public string NameBook { get; set; }
    
        public virtual ICollection<AuthorBooks> AuthorBooks { get; set; }
        public virtual ICollection<Loans> Loans { get; set; }
    }
}
