//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotekka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loans
    {
        public Loans()
        {
            this.Returns = new HashSet<Returns>();
        }
    
        public int id { get; set; }
        public int ReadersID { get; set; }
        public int BooksID { get; set; }
        public System.DateTime LoanDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public bool IsReturned { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Readers Readers { get; set; }
        public virtual ICollection<Returns> Returns { get; set; }
    }
}
