//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotekka
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities4 : DbContext
    {
        public Entities4()
            : base("name=Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Author { get; set; }
        public DbSet<AuthorBooks> AuthorBooks { get; set; }
        public DbSet<Books> Books { get; set; }
        public DbSet<Loans> Loans { get; set; }
        public DbSet<Readers> Readers { get; set; }
        public DbSet<Returns> Returns { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
