//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bibliotekka
{
    using System;
    using System.Collections.Generic;
    
    public partial class Returns
    {
        public int id { get; set; }
        public int LoansID { get; set; }
        public System.DateTime ReturnDate { get; set; }
    
        public virtual Loans Loans { get; set; }
    }
}
